version: "3"
services:
    
    python-dev:
        container_name: flask-server
        build:
            context: app/
            dockerfile: Dockerfile
        volumes:
            - /app:/var/app/flask_app
        ports:
            - 8000:8000
    mysql-dev:
        platform: linux/x86_64
        image: mysql:8.0
        container_name: flask-db
        ports:
            - 6603:3306
        environment:
            MYSQL_ROOT_PASSWORD: "root"
        volumes:
            - /Users/emirbalkan/Desktop/mysql-datadirectory:/var/lib/mysql
    adminer:
        image: adminer
        container_name: flask-adminer
        restart: always
        ports:
            - 8080:8080
        links:
            - mysql-dev    
volumes:
    database-folder:          
